
server:
  port: 8082

spring:
  application:
    name: kafkaproducer
#  kafka:
#    producer:
#      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002 # ??? ?? ??
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: error-handler-group
#      auto-offset-reset: earliest
#    template:
#      default-topic: error-messages